version: '3.8'
services:
    php-apache-environment:
        container_name: reticula_isc
        build:
            context: ./src
            dockerfile: DockerFile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 6060:80
    db:
      container_name: db_isc
      image: mysql
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: " " 
          MYSQL_DATABASE: "reticulaisc"
          MYSQL_USER: "salmahg"
          MYSQL_PASSWORD: " "
      ports:
          - "9906:3306"